# basic configuration
baseurl: https://brownbiostats.github.io/php2511/r
markdown: kramdown
permalink: /:categories/:title/


# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#05C6B4"
jumbotron_background_image: "header.svg"
jumbotron_image: "box-icon.png"
